### ISSUE TITLE
Arrumar página inicial do Pages

### ISSUE THREAD

**Issue by BeatrizHanae** [Dulce-Work-Schedule/Dulce-Work-Schedule.github.io#5]
Conteúdo da *issue*
 Arrumar a página inicial do pages de acordo com o app Atual.

Nessa issue será realizado:
- Descrição inicial, logo após o nome;
- Fotos e vídeos interativos do app;
- Explicações do app.

Critérios de aceitação:
- Visual;
- Ortografia.

**Comment by egewarth** [comment]
https://getbootstrap.com/docs/4.1/content/images/#responsive-images

**Comment by fepas** [comment]
Faremos algumas mudanças no pages, por esse motivo, reabriremos o PR:
